spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/stock?serverZone=Asia/Seoul
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9094
    security:
      protocol:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

kafka-dead-letter: stock-dead-letter